/*
 * This file is generated by jOOQ.
*/
package home.maks.db.model.tables.records;


import home.maks.db.model.tables.FileContent;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileContentRecord extends TableRecordImpl<FileContentRecord> implements Record14<Integer, Integer, String, Timestamp, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1460381075;

    /**
     * Setter for <code>TZ.FILE_CONTENT.FILE_ID</code>.
     */
    public void setFileId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>TZ.FILE_CONTENT.FILE_ID</code>.
     */
    public Integer getFileId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TZ.FILE_CONTENT.SEQ_ID</code>.
     */
    public void setSeqId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>TZ.FILE_CONTENT.SEQ_ID</code>.
     */
    public Integer getSeqId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>TZ.FILE_CONTENT.SSOID</code>.
     */
    public void setSsoid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>TZ.FILE_CONTENT.SSOID</code>.
     */
    public String getSsoid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>TZ.FILE_CONTENT.TS</code>.
     */
    public void setTs(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>TZ.FILE_CONTENT.TS</code>.
     */
    public Timestamp getTs() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>TZ.FILE_CONTENT.GRP</code>.
     */
    public void setGrp(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>TZ.FILE_CONTENT.GRP</code>.
     */
    public String getGrp() {
        return (String) get(4);
    }

    /**
     * Setter for <code>TZ.FILE_CONTENT.TYPE</code>.
     */
    public void setType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>TZ.FILE_CONTENT.TYPE</code>.
     */
    public String getType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>TZ.FILE_CONTENT.SUBTYPE</code>.
     */
    public void setSubtype(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>TZ.FILE_CONTENT.SUBTYPE</code>.
     */
    public String getSubtype() {
        return (String) get(6);
    }

    /**
     * Setter for <code>TZ.FILE_CONTENT.URL</code>.
     */
    public void setUrl(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>TZ.FILE_CONTENT.URL</code>.
     */
    public String getUrl() {
        return (String) get(7);
    }

    /**
     * Setter for <code>TZ.FILE_CONTENT.ORGID</code>.
     */
    public void setOrgid(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>TZ.FILE_CONTENT.ORGID</code>.
     */
    public String getOrgid() {
        return (String) get(8);
    }

    /**
     * Setter for <code>TZ.FILE_CONTENT.FORMID</code>.
     */
    public void setFormid(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>TZ.FILE_CONTENT.FORMID</code>.
     */
    public String getFormid() {
        return (String) get(9);
    }

    /**
     * Setter for <code>TZ.FILE_CONTENT.CODE</code>.
     */
    public void setCode(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>TZ.FILE_CONTENT.CODE</code>.
     */
    public String getCode() {
        return (String) get(10);
    }

    /**
     * Setter for <code>TZ.FILE_CONTENT.LTPA</code>.
     */
    public void setLtpa(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>TZ.FILE_CONTENT.LTPA</code>.
     */
    public String getLtpa() {
        return (String) get(11);
    }

    /**
     * Setter for <code>TZ.FILE_CONTENT.SUDIRRESPONSE</code>.
     */
    public void setSudirresponse(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>TZ.FILE_CONTENT.SUDIRRESPONSE</code>.
     */
    public String getSudirresponse() {
        return (String) get(12);
    }

    /**
     * Setter for <code>TZ.FILE_CONTENT.YMDH</code>.
     */
    public void setYmdh(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>TZ.FILE_CONTENT.YMDH</code>.
     */
    public String getYmdh() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, Integer, String, Timestamp, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, Integer, String, Timestamp, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return FileContent.FILE_CONTENT.FILE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return FileContent.FILE_CONTENT.SEQ_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return FileContent.FILE_CONTENT.SSOID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return FileContent.FILE_CONTENT.TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return FileContent.FILE_CONTENT.GRP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return FileContent.FILE_CONTENT.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return FileContent.FILE_CONTENT.SUBTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return FileContent.FILE_CONTENT.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return FileContent.FILE_CONTENT.ORGID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return FileContent.FILE_CONTENT.FORMID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return FileContent.FILE_CONTENT.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return FileContent.FILE_CONTENT.LTPA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return FileContent.FILE_CONTENT.SUDIRRESPONSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return FileContent.FILE_CONTENT.YMDH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getFileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getSeqId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSsoid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getGrp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getSubtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getOrgid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getFormid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getLtpa();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getSudirresponse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getYmdh();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getFileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSeqId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSsoid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getGrp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getSubtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getOrgid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getFormid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getLtpa();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getSudirresponse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getYmdh();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileContentRecord value1(Integer value) {
        setFileId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileContentRecord value2(Integer value) {
        setSeqId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileContentRecord value3(String value) {
        setSsoid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileContentRecord value4(Timestamp value) {
        setTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileContentRecord value5(String value) {
        setGrp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileContentRecord value6(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileContentRecord value7(String value) {
        setSubtype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileContentRecord value8(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileContentRecord value9(String value) {
        setOrgid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileContentRecord value10(String value) {
        setFormid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileContentRecord value11(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileContentRecord value12(String value) {
        setLtpa(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileContentRecord value13(String value) {
        setSudirresponse(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileContentRecord value14(String value) {
        setYmdh(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileContentRecord values(Integer value1, Integer value2, String value3, Timestamp value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FileContentRecord
     */
    public FileContentRecord() {
        super(FileContent.FILE_CONTENT);
    }

    /**
     * Create a detached, initialised FileContentRecord
     */
    public FileContentRecord(Integer fileId, Integer seqId, String ssoid, Timestamp ts, String grp, String type, String subtype, String url, String orgid, String formid, String code, String ltpa, String sudirresponse, String ymdh) {
        super(FileContent.FILE_CONTENT);

        set(0, fileId);
        set(1, seqId);
        set(2, ssoid);
        set(3, ts);
        set(4, grp);
        set(5, type);
        set(6, subtype);
        set(7, url);
        set(8, orgid);
        set(9, formid);
        set(10, code);
        set(11, ltpa);
        set(12, sudirresponse);
        set(13, ymdh);
    }
}
