/*
 * This file is generated by jOOQ.
*/
package home.maks.db.model.tables.records;


import home.maks.db.model.tables.FormStat;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FormStatRecord extends TableRecordImpl<FormStatRecord> implements Record4<Integer, Integer, String, Integer> {

    private static final long serialVersionUID = -919694750;

    /**
     * Setter for <code>TZ.FORM_STAT.FILE_ID</code>.
     */
    public void setFileId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>TZ.FORM_STAT.FILE_ID</code>.
     */
    public Integer getFileId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TZ.FORM_STAT.SEQ_ID</code>.
     */
    public void setSeqId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>TZ.FORM_STAT.SEQ_ID</code>.
     */
    public Integer getSeqId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>TZ.FORM_STAT.FORMID</code>.
     */
    public void setFormid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>TZ.FORM_STAT.FORMID</code>.
     */
    public String getFormid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>TZ.FORM_STAT.COUNT</code>.
     */
    public void setCount(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>TZ.FORM_STAT.COUNT</code>.
     */
    public Integer getCount() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return FormStat.FORM_STAT.FILE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return FormStat.FORM_STAT.SEQ_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return FormStat.FORM_STAT.FORMID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return FormStat.FORM_STAT.COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getFileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getSeqId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getFormid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getFileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSeqId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFormid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FormStatRecord value1(Integer value) {
        setFileId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FormStatRecord value2(Integer value) {
        setSeqId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FormStatRecord value3(String value) {
        setFormid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FormStatRecord value4(Integer value) {
        setCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FormStatRecord values(Integer value1, Integer value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FormStatRecord
     */
    public FormStatRecord() {
        super(FormStat.FORM_STAT);
    }

    /**
     * Create a detached, initialised FormStatRecord
     */
    public FormStatRecord(Integer fileId, Integer seqId, String formid, Integer count) {
        super(FormStat.FORM_STAT);

        set(0, fileId);
        set(1, seqId);
        set(2, formid);
        set(3, count);
    }
}
