/*
 * This file is generated by jOOQ.
*/
package home.maks.db.model.tables.records;


import home.maks.db.model.tables.UserStat;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserStatRecord extends TableRecordImpl<UserStatRecord> implements Record4<Integer, Integer, String, String> {

    private static final long serialVersionUID = -1616086300;

    /**
     * Setter for <code>TZ.USER_STAT.FILE_ID</code>.
     */
    public void setFileId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>TZ.USER_STAT.FILE_ID</code>.
     */
    public Integer getFileId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TZ.USER_STAT.SEQ_ID</code>.
     */
    public void setSeqId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>TZ.USER_STAT.SEQ_ID</code>.
     */
    public Integer getSeqId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>TZ.USER_STAT.SSOID</code>.
     */
    public void setSsoid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>TZ.USER_STAT.SSOID</code>.
     */
    public String getSsoid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>TZ.USER_STAT.FORMID</code>.
     */
    public void setFormid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>TZ.USER_STAT.FORMID</code>.
     */
    public String getFormid() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserStat.USER_STAT.FILE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserStat.USER_STAT.SEQ_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UserStat.USER_STAT.SSOID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UserStat.USER_STAT.FORMID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getFileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getSeqId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSsoid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getFormid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getFileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSeqId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSsoid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFormid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserStatRecord value1(Integer value) {
        setFileId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserStatRecord value2(Integer value) {
        setSeqId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserStatRecord value3(String value) {
        setSsoid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserStatRecord value4(String value) {
        setFormid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserStatRecord values(Integer value1, Integer value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserStatRecord
     */
    public UserStatRecord() {
        super(UserStat.USER_STAT);
    }

    /**
     * Create a detached, initialised UserStatRecord
     */
    public UserStatRecord(Integer fileId, Integer seqId, String ssoid, String formid) {
        super(UserStat.USER_STAT);

        set(0, fileId);
        set(1, seqId);
        set(2, ssoid);
        set(3, formid);
    }
}
