/*
 * This file is generated by jOOQ.
*/
package home.maks.db.model;


import home.maks.db.model.tables.FileContent;
import home.maks.db.model.tables.FormStat;
import home.maks.db.model.tables.UserStat;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>TZ</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index NX_FILECONTENT_FILEID_TS = Indexes0.NX_FILECONTENT_FILEID_TS;
    public static final Index NX_FILECONTENT_FILEID_FORMID = Indexes0.NX_FILECONTENT_FILEID_FORMID;
    public static final Index NX_FORMSTAT_FILEID_SEQID = Indexes0.NX_FORMSTAT_FILEID_SEQID;
    public static final Index NX_USERSTAT_FILEID_SEQID = Indexes0.NX_USERSTAT_FILEID_SEQID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index NX_FILECONTENT_FILEID_TS = Internal.createIndex("NX_FILECONTENT_FILEID_TS", FileContent.FILE_CONTENT, new OrderField[] { FileContent.FILE_CONTENT.FILE_ID, FileContent.FILE_CONTENT.TS }, false);
        public static Index NX_FILECONTENT_FILEID_FORMID = Internal.createIndex("NX_FILECONTENT_FILEID_FORMID", FileContent.FILE_CONTENT, new OrderField[] { FileContent.FILE_CONTENT.FILE_ID, FileContent.FILE_CONTENT.FORMID }, false);
        public static Index NX_FORMSTAT_FILEID_SEQID = Internal.createIndex("NX_FORMSTAT_FILEID_SEQID", FormStat.FORM_STAT, new OrderField[] { FormStat.FORM_STAT.FILE_ID, FormStat.FORM_STAT.SEQ_ID }, false);
        public static Index NX_USERSTAT_FILEID_SEQID = Internal.createIndex("NX_USERSTAT_FILEID_SEQID", UserStat.USER_STAT, new OrderField[] { UserStat.USER_STAT.FILE_ID, UserStat.USER_STAT.SEQ_ID }, false);
    }
}
