/*
 * This file is generated by jOOQ.
*/
package home.maks.db.model;


import home.maks.db.model.tables.File;
import home.maks.db.model.tables.records.FileRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>TZ</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<FileRecord, Integer> IDENTITY_FILE = Identities0.IDENTITY_FILE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FileRecord> PK_FILE_FILEID = UniqueKeys0.PK_FILE_FILEID;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<FileRecord, Integer> IDENTITY_FILE = Internal.createIdentity(File.FILE, File.FILE.FILE_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<FileRecord> PK_FILE_FILEID = Internal.createUniqueKey(File.FILE, "PK_FILE_FILEID", File.FILE.FILE_ID);
    }
}
