/*
 * This file is generated by jOOQ.
*/
package home.maks.db.model;


import home.maks.db.model.tables.File;
import home.maks.db.model.tables.FileContent;
import home.maks.db.model.tables.FormStat;
import home.maks.db.model.tables.UserStat;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tz extends SchemaImpl {

    private static final long serialVersionUID = -887851679;

    /**
     * The reference instance of <code>TZ</code>
     */
    public static final Tz TZ = new Tz();

    /**
     * The table <code>TZ.FILE</code>.
     */
    public final File FILE = home.maks.db.model.tables.File.FILE;

    /**
     * The table <code>TZ.FILE_CONTENT</code>.
     */
    public final FileContent FILE_CONTENT = home.maks.db.model.tables.FileContent.FILE_CONTENT;

    /**
     * The table <code>TZ.FORM_STAT</code>.
     */
    public final FormStat FORM_STAT = home.maks.db.model.tables.FormStat.FORM_STAT;

    /**
     * The table <code>TZ.USER_STAT</code>.
     */
    public final UserStat USER_STAT = home.maks.db.model.tables.UserStat.USER_STAT;

    /**
     * No further instances allowed
     */
    private Tz() {
        super("TZ", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            File.FILE,
            FileContent.FILE_CONTENT,
            FormStat.FORM_STAT,
            UserStat.USER_STAT);
    }
}
